version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:password@postgres-db/
      - SECRET_KEY_BASE=e57c3aa8df021629befb0d6fb09f7fe112c4c16c55858404ff9518b310b7f0b5f2b111cf155a233b58d258dac811f44b352e7cba15bae13b2b92cc7c8882822f
    secrets:
      - source: master_key
        target: /rails/config/master.key
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30

secrets:
  master_key:
    file: ./config/master.key